  --- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: drupal-mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template: 
    metadata: 
      labels: 
        app: drupal-mysql
    spec: 
      containers: 
        - 
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-secret
                  key: MYSQL_USER
          image: "mysql:5.7"
          name: cont-drupal-mysql
          ports: 
            - 
              containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /var/lib/mysql
              name: vol-drupal
              subPath: dbdata
      volumes: 
        - 
          name: vol-drupal
          persistentVolumeClaim: 
            claimName: drupal-mysql-pvc

--- 
apiVersion: v1
kind: Service
metadata: 
  name: drupal-mysql-service
spec: 
  ports: 
    - 
      name: mysql
      port: 3306
      protocol: TCP
  selector: 
    app: drupal-mysql