---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# COMMENT THE CODE ABOVE AND UNCOMMENT THE CODE UNDER THIS LINE

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: drupal-mysql-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi